MasterPiece/MasterPiece/Models/Appointment.cs
using System;
using System.Collections.Generic;

namespace MasterPiece.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int? OwnerId { get; set; }

    public int? ClinicId { get; set; }

    public int? ServiceTypeId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public DateTime AppointmentTime { get; set; }

    public string? Status { get; set; }

    public string? Description { get; set; }

    public string? OwnerName { get; set; }

    public string? OwnerPhone { get; set; }

    public string? PetType { get; set; }

    public string? ClinicName { get; set; }

    public string? ServiceName { get; set; }

    public virtual Clinic? Clinic { get; set; }

    public virtual PetOwner? Owner { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ServiceType? ServiceType { get; set; }

    public virtual ICollection<TransportRequest> TransportRequests { get; set; } = new List<TransportRequest>();
}

MasterPiece/MasterPiece/Models/Clinic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MasterPiece.Models;

public partial class Clinic
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Location { get; set; } = null!;

    public string? Phone { get; set; }

    public string? Email { get; set; }

    public string? Image { get; set; }

    public string? Description { get; set; }

    public string? WorkingHours { get; set; }

    public int? Rating { get; set; }

    public string Category { get; set; } = null!;

    public string? Image1 { get; set; }

    public string? Image2 { get; set; }

    public string? Image3 { get; set; }

    [NotMapped]
    public IFormFile ImageFile { get; set; }
    [NotMapped]
    public IFormFile ImageFile1 { get; set; }
    [NotMapped]
    public IFormFile ImageFile2 { get; set; }
    [NotMapped]
    public IFormFile ImageFile3 { get; set; }
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    public virtual ICollection<Vet> Vets { get; set; } = new List<Vet>();
}

MasterPiece/MasterPiece/Controllers/ClinicsController.cs
using MasterPiece.Models;
using MasterPiece.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MasterPiece.Controllers
{
    public class ClinicsController : Controller
    {
        private readonly MyDbContext _context;

        public ClinicsController(MyDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.Clinics.ToList());

        }
        [HttpGet]
        public IActionResult GetClinicsByLocation(string location)
        {
            var clinics = _context.Clinics.AsQueryable();

            if (!string.IsNullOrEmpty(location) && location.ToLower() != "all")
            {
                clinics = clinics.Where(c => c.Location.ToLower() == location.ToLower());
            }

            return Json(clinics.ToList());
        }

        [HttpGet]
        public IActionResult SearchClinics(string query)
        {
            var clinics = _context.Clinics
                .Where(c => c.Name.Contains(query))
                .ToList();

            return Json(clinics);
        }


      

  public IActionResult ClinicDetails(int id)
        {
          
            var clinic = _context.Clinics.FirstOrDefault(c => c.Id == id);
            TempData["ClinicId"] = clinic.Id;
            TempData["ClinicName"] = clinic.Name;   
            if (clinic == null)
            {
                return NotFound();
            }
            return View(clinic);


        }


        public IActionResult ClinicServices(int id)
        {
            var serviceTypes = _context.ServiceTypes.Where(s => s.ServiceId == id).ToList();

            if (serviceTypes == null || serviceTypes.Count == 0)
            {
                return NotFound(); 
            }

            return View(serviceTypes);
        }

        //public IActionResult Appointment()
        //{

        //    return View();

        //}

        public IActionResult Appointment(int? serviceId)
        {
            var UserId = HttpContext.Session.GetInt32("UserId");
            Console.WriteLine("UserId", UserId);



            if (UserId == null)
            {
                return RedirectToAction("LoginUser", "User"); // إذا لم يكن هناك جلسة، إعادة توجيه إلى صفحة تسجيل الدخول
            }

            if (serviceId.HasValue)
            {
                var selectedService = _context.ServiceTypes.FirstOrDefault(s => s.Id == serviceId.Value);
                if (selectedService != null)
                {
                    var viewModel = new ServiceTypeAppointment
                    {
                        ServiceId = selectedService.Id,
                        PetType = selectedService.PetType,
                        ServiceName = selectedService.Name,
                        Price = selectedService.Price,
                        Img = selectedService.Img
                    };

                    return View(viewModel);
                }
            }

            return View(new ServiceTypeAppointment()); // في حال ما تم اختيار خدمة
        }

        [HttpPost]
        public IActionResult Appointment(Appointment Formdata)
        {
            int? ownerId = HttpContext.Session.GetInt32("UserId");
            int? clinicId = TempData["ClinicId"] as int?;
            string? clinicName = TempData["ClinicName"] as string;

            var appointment = new Appointment
            {
                OwnerId = ownerId.Value,
                ClinicId = clinicId.Value,
                ClinicName = clinicName,
                OwnerName = Formdata.OwnerName,
                OwnerPhone = Formdata.OwnerPhone,
                PetType = Formdata.PetType,
                ServiceName = Formdata.ServiceName,
                AppointmentDate = Formdata.AppointmentDate,
                AppointmentTime = Formdata.AppointmentTime,
                Description = Formdata.Description,
                Status = "Pending",
            };

            _context.Appointments.Add(appointment);
            _context.SaveChanges();

            // إعداد ViewModel للتأكيد
            var service = _context.ServiceTypes.FirstOrDefault(s => s.Name == Formdata.ServiceName);

            var viewModel = new ServiceTypeAppointment
            {
                Id = appointment.Id,
                OwnerName = appointment.OwnerName,
                OwnerPhone = appointment.OwnerPhone,
                PetType = appointment.PetType,
                AppointmentDate = appointment.AppointmentDate,
                AppointmentTime = appointment.AppointmentTime,
                ServiceName = appointment.ServiceName,
                ClinicName = appointment.ClinicName,
                Price = service?.Price ?? 0,
                Img = service?.Img
            };
            return RedirectToAction("PaymentPage", new { appointmentId = appointment.Id });
            //return View("ConfirmAppointment", viewModel); // توجيه إلى صفحة التأكيد
        }




        //////////////////////////
        //public IActionResult PaymentPage(int appointmentId)
        //{
        //    var appointment = _context.Appointments.FirstOrDefault(a => a.Id == appointmentId);
        //    if (appointment == null)
        //        return NotFound();

        //    // استرجاع بيانات الخدمة
        //    var service = _context.ServiceTypes.FirstOrDefault(s => s.Name == appointment.ServiceName);

        //    var viewModel = new PaymentViewModel
        //    {
        //        AppointmentId = appointment.Id,
        //        OwnerId = appointment.OwnerId ?? 0,
        //        Amount = service?.Price ?? 0, // السعر الحقيقي
        //        AppointmentDate = appointment.AppointmentDate.ToString("yyyy-MM-dd HH:mm"),
        //        ClinicName = appointment.ClinicName // اسم العيادة المخزن
        //    };

        //    return View(viewModel);
        //}
        public IActionResult PaymentPage(int appointmentId)
        {
            var appointment = _context.Appointments.FirstOrDefault(a => a.Id == appointmentId);
            if (appointment == null)
                return NotFound();

            // استرجاع بيانات الخدمة
            var service = _context.ServiceTypes.FirstOrDefault(s => s.Name == appointment.ServiceName);
            decimal basePrice = service?.Price ?? 0;

            // حساب السعر مع إضافة نسبة 20%
            decimal commissionPercentage = 0.20m;
            decimal totalPrice = basePrice + (basePrice * commissionPercentage);

            var viewModel = new PaymentViewModel
            {
                AppointmentId = appointment.Id,
                OwnerId = appointment.OwnerId ?? 0,
                Amount = totalPrice, // السعر النهائي بعد العمولة
                AppointmentDate = appointment.AppointmentDate.ToString("yyyy-MM-dd HH:mm"),
                ClinicName = appointment.ClinicName
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult SubmitPayment(PaymentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var payment = new Payment
                {
                    AppointmentId = model.AppointmentId,
                    OwnerId = model.OwnerId,
                    Amount = model.Amount,
                    PaymentMethod = model.PaymentMethod,
                    PaymentStatus = "Paid"
                };

                _context.Payments.Add(payment);
                _context.SaveChanges();


                 TempData["SuccessMessage"] = "Appointment booked successfully!";
                 return RedirectToAction("Appointment");
            }

            return View("PaymentPage", model);
        }
        public IActionResult Confirmation()
        {
            return View(); // صفحة تأكيد الدفع
        }
        //[HttpPost]
        //public IActionResult Appointment(Appointment Formdata)
        //{
        //    //int ownerId = (int)HttpContext.Session.GetInt32("UserId");
        //    int? ownerId = 1;
        //    int? clinicId = TempData["ClinicId"] as int?;
        //    string? clinicName = TempData["ClinicName"] as string;
        //    var appointment = new Appointment
        //    {
        //        OwnerId = ownerId.Value, // إضافة OwnerId
        //        ClinicId = clinicId.Value, // إضافة ClinicId
        //        ClinicName = clinicName,
        //        OwnerName = Formdata.OwnerName,
        //        OwnerPhone = Formdata.OwnerPhone,
        //        PetType = Formdata.PetType,
        //        ServiceName = Formdata.ServiceName,
        //        AppointmentDate = Formdata.AppointmentDate,
        //        AppointmentTime = Formdata.AppointmentTime,
        //        Description = Formdata.Description,
        //        Status = "Pending",// تعيين الحالة الافتراضية للحجز

        //    };
        //    _context.Appointments.Add(appointment);
        //    _context.SaveChanges();

        //    TempData["SuccessMessage"] = "Appointment booked successfully!";
        //    return RedirectToAction("Appointment");
        //}







    }
}

MasterPiece/MasterPiece/Views/Clinics/Appointment.cshtml
@using MasterPiece.ViewModel

@model ServiceTypeAppointment 


@section Styles {
    <link rel="stylesheet" href="~/css/Appointment.css" />
}

@* @section Scripts { *@
@*     <script src="~/js/site.js"></script> *@
@*     <script> *@
@*         document.addEventListener("DOMContentLoaded", function () { *@
@*             var successMessage = '@TempData["SuccessMessage"]'; *@
@*             if (successMessage) { *@
@*                 Swal.fire({ *@
@*                     icon: 'success', *@
@*                     title: 'Done!', *@
@*                     text: successMessage, *@
@*                     confirmButtonColor: '#A294F9' *@
@*                 }); *@
@*             } *@
@*         }); *@
@*     </script> *@

@* } *@

<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs d-flex align-items-center" style="background-color: #e6e3fb;">
    <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Appointment</h2>

    </div>
</div><!-- End Breadcrumbs -->
<!-- Appointment Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="margin-top: 10%;">
                <p class="d-inline-block border rounded-pill py-1 px-4">Appointment</p>
                <h1 class="mb-4">Make An Appointment To Visit Clinic</h1>
                <p class="mb-4">Fill out the form below to schedule a service for your pet. Please provide your contact information and the needed service. We’ll get back to you shortly to confirm your appointment.</p>
                <div class=" rounded d-flex align-items-center p-5 mb-4" style="background-color: #e6e3fb;">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-white" style="width: 55px; height: 55px;">
                        <i class="fa fa-phone-alt " style="color: #A294F9;"></i>
                    </div>
                    <div class="ms-4">
                        <p class="mb-2">Call Us Now</p>
                        <h5 class="mb-0">+012 345 6789</h5>
                    </div>
                </div>
                <div class=" rounded d-flex align-items-center p-5" style="background-color: #e6e3fb;">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-white" style="width: 55px; height: 55px;">
                        <i class="fa fa-envelope-open " style="color: #A294F9;"></i>
                    </div>
                    <div class="ms-4">
                        <p class="mb-2">Mail Us Now</p>
                        <h5 class="mb-0">PetNet@gmail.com</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s" style="margin-top: 10%;">
                <!-- <img src="Img/AppointmentPhoto.png" style="width: 40%;height: 20%;margin-left: 60%;"> -->
                <div class=" rounded h-100 d-flex align-items-center p-5" style="background-color: #e6e3fb;">
                    <form asp-action="Appointment" method="post">
                        <div class="row g-3">
                            <div class="col-12 col-sm-6">
                                <input asp-for="OwnerName" class="form-control" placeholder="Your Name" required style="height: 55px;">
                            </div>
                            <div class="col-12 col-sm-6">
                                <input asp-for="OwnerPhone" class="form-control" placeholder="Your Mobile" required style="height: 55px;">
                            </div>
                            <!-- <div class="col-12 col-sm-6">
                                <input type="text" class="form-control border-0" placeholder="Pet Type" style="height: 55px;">
                            </div> -->
                            @* <div class="col-12 col-sm-6"> *@
                                @* <select asp-for="PetType" class="form-select"> *@
                                @*     <option selected disabled>Pet Type</option> *@
                                @*     <option value="Cat">Cat</option> *@
                                @*     <option value="Dog">Dog</option> *@
                                @*     <option value="Rabbit">Rabbit</option> *@
                                @* </select> *@
                                @if (Model.PetType != null)
                                {
                                    <div class="col-12 col-sm-6">
                                        <input type="text" class="form-control" value="@Model.PetType" readonly />
                                        <input type="hidden" asp-for="PetType" />
                                    </div>
                                }
                            @* </div> *@
                            @* <div class="col-12 col-sm-6">  *@
                            @*   <select asp-for="ServiceName" class="form-select">  *@
                            @*         <option selected disabled>Choose Service</option>  *@
                            @*        <option value="Vaccination">Vaccination</option>  *@
                            @*        <option value="Grooming">Grooming</option>  *@
                            @*            <option value="Surgery">Surgery</option>  *@
                            @*      <option value="Dental Care">Dental Care</option>  *@
                            @*         <option value="Check-Ups">Check-Ups</option>  *@
                            @*     </select>  *@
                            @* </div> *@
                            @if (Model.ServiceName != null)
                            {
                                <div class="col-12 col-sm-6">
                                    <input type="text" class="form-control" value="@Model.ServiceName" readonly />
                                    <input type="hidden" asp-for="ServiceName" />
                                </div>
                            }
                            else
                            {
                                <div class="col-12 col-sm-6">
                                    <select asp-for="ServiceName" class="form-select">
                                        <option selected disabled>Choose Service</option>
                                        <option value="Vaccination">Vaccination</option>
                                        <option value="Grooming">Grooming</option>
                                        <option value="Surgery">Surgery</option>
                                        <option value="Dental Care">Dental Care</option>
                                        <option value="Check-Ups">Check-Ups</option>
                                    </select>
                                </div>
                            }
                            <div class="col-12 col-sm-6">
                                <div class="date" id="date" data-target-input="nearest">
                                    <input asp-for="AppointmentDate" type="date" class="form-control" required style="height: 55px;">
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="time" id="time" data-target-input="nearest">
                                    <input asp-for="AppointmentTime" type="time" class="form-control" required style="height: 55px;">
                                </div>
                            </div>
                            <div class="col-12">
                                <textarea asp-for="Description" class="form-control" rows="3" placeholder="Describe your problem"></textarea>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn  w-100 py-3" style="background-color:#CDC1FF ;color:white;">Book Appointment</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Appointment End -->

MasterPiece/MasterPiece/Views/Clinics/ClinicDetails.cshtml
@model MasterPiece.Models.Clinic

@section Styles {
    <link rel="stylesheet" href="~/css/ClinicDetails.css" />
}

@section Scripts {
    <script src="~/js/site.js"></script>
}


<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs d-flex align-items-center" style="background-color: #e6e3fb;">
    <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Clinic Details</h2>

    </div>
</div><!-- End Breadcrumbs -->



<div class="container">

    <div class="grid product">
        <div class="column-xs-12 column-md-7">
            <div class="product-gallery">
                <div class="product-image">
                    <img class="active" src="~/Img/@Model.Image">
                </div>
                <ul class="image-list">
                    <li class="image-item"><img src="~/Img/@Model.Image1"></li>
                    <li class="image-item"><img src="~/Img/@Model.Image2"></li>
                    <li class="image-item"><img src="~/Img/@Model.Image3"></li>
                </ul>
            </div>
        </div>
        <br>
        <div class="column-xs-12 column-md-5" style="margin-top: 5%;">
            <h1>@Model.Name</h1><br><br><br>
            <h6>
                <div style="display: flex;">
                    <i class="fa-solid fa-location-dot" style=" color: #A294F9;"></i>
                    <p style="margin-left: 5px; "> <span style="font-weight: bold;"> Location:</span> @Model.Location</p>
                </div>
                <div style="display: flex;">
                    <i class="fa-solid fa-clock" style=" color: #A294F9;"></i>
                    <p style="margin-left: 5px ;"> <span style="font-weight: bold;">  Working hours :</span> @Model.WorkingHours</p>
                </div>
            </h6>
            <br />
            <div class="description">
                <br>
                <br>
                <p>@Model.Description.</p>
                <a asp-controller="Clinics" asp-action="Appointment" asp-route-serviceId="@Model.Id" class="btn btn-primary">
                    Book Now
                </a>
            </div>
           
        </div>
    </div>
    <br>
    <br>

    <h2 style="text-align:center !important;"> Services</h2>

    <div class="categories">
        <div class="category" style="background-color: #fff8e1;">
            <img src="~/Img/vaccination.png" alt="vaccination">
            @* <h3>Vaccination</h3> *@
            <a asp-controller="Clinics" asp-action="ClinicServices" asp-route-id="1">Vaccination</a>
        </div>

        <div class="category" style="background-color: #e8f5e9;">
            <img src="~/Img/grooming.png" alt="Grooming">
            @* <h3>Grooming</h3> *@
            <a asp-controller="Clinics" asp-action="ClinicServices" asp-route-id="2">Grooming</a>
        </div>

        <div class="category" style="background-color: #e3f2fd;">
            <img src="~/Img/sergery.png" alt="Fish">
            @* <h3>Surgery</h3> *@
            <a asp-controller="Clinics" asp-action="ClinicServices" asp-route-id="3">Surgery</a>
        </div>

        <div class="category" style="background-color: #fce4ec;">
            <img src="~/Img/dental.png" alt="Bird">
            @* <h3>Dental Care</h3> *@
            <a asp-controller="Clinics" asp-action="ClinicServices" asp-route-id="4">Dental Care</a>
        </div>

        <div class="category" style="background-color: #f3e5f5;">
            <img src="~/Img/checkUp.png" alt="Hamster">
            @* <h3>Check-Ups</h3> *@
            <a asp-controller="Clinics" asp-action="ClinicServices" asp-route-id="5">Check-Ups</a>
        </div>
    </div>

   

MasterPiece/MasterPiece/Views/Clinics/ClinicServices.cshtml
@model List<ServiceType>

@section Styles {
    <link rel="stylesheet" href="~/css/ClinicDetails.css" />
}

@section Scripts {
    <script src="~/js/site.js"></script>
}

<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs d-flex align-items-center" style="background-color: #e6e3fb;">
    <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">
        <h2>Available Services</h2>
    </div>
</div>
<!-- End Breadcrumbs -->





<!-- القوائم المنسدلة على اليمين -->
<div class="d-flex gap-3 flex-wrap" style="margin-top: 3%; margin-left: 16%;margin-bottom: 3%;">


    <!-- فلترة حسب الموقع -->
    <div class="dropdown">
        <button class="btn dropdown-toggle properties-filter" type="button" data-bs-toggle="dropdown" aria-expanded="false" style=" background-color:#CDC1FF;">
            Filter by PetType
        </button>
        <ul class="dropdown-menu " id="locationFilter">
            <li><a class="dropdown-item" href="#" data-location="all">Show All</a></li>
            <li><a class="dropdown-item" href="#" data-location="Cats">Cats</a></li>
            <li><a class="dropdown-item" href="#" data-location="Dogs">Dogs</a></li>
            <li><a class="dropdown-item" href="#" data-location="Rbbits">Rabbits</a></li>
            
        </ul>
    </div>

</div>



<div class="container">
    <div class="grid related-products">
        <div class="column-xs-12">
        </div>

        @foreach (var service in Model)
        {
            <div class="column-xs-12 column-md-4 servimg">
                <img src="~/Img/@service.Img" alt="@service.Name"><br />
                <h5>@service.Name</h5>
                <br />
                 <p>PetType : @service.PetType</p>
            
                <p>Price: @service.Price JD</p>
                <a asp-controller="Clinics" asp-action="Appointment" asp-route-serviceId="@service.Id" class="btn btn-primary"> 
                    Book Now 
                </a>
            </div>
        }
    </div>
</div>

MasterPiece/MasterPiece/Views/Clinics/Confirmation.cshtml
@{
    ViewData["Title"] = "Confirmation";
}

<div class="container mt-5">
    <div class="alert alert-success text-center">
        <h4>✅ تم الدفع بنجاح!</h4>
        <p>شكراً لحجزك معنا.</p>
        <a href="/" class="btn btn-success mt-3">العودة للصفحة الرئيسية</a>
    </div>
</div>

MasterPiece/MasterPiece/Views/Clinics/Index.cshtml
@model List<Clinic>

@section Styles {
    <link rel="stylesheet" href="~/css/Clinics.css" />
}

@section Scripts {
    <script src="~/js/site.js"></script>
    <script src="~/js/filter.js"></script>
    <script src="~/js/search.js"></script>
}


<div class="page-heading header-text" style="background-color: #e6e3fb;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Clinics</h3>
            </div>
        </div>
    </div>
</div>



<div class="section properties" style="margin-top: 42px;">
    <div class="container">
      
        <div class="row" style="margin-bottom:10%">
            <div class="col-lg-12">
                <div class="axil-shop-top">
                    <div class="d-flex justify-content-between align-items-center flex-wrap">

                        <!-- القوائم المنسدلة على اليمين -->
                        <div class="d-flex gap-3 flex-wrap">

                            <!-- فلترة حسب التقييم -->
                            <div class="dropdown">
                                <button class="btn dropdown-toggle properties-filter" type="button" data-bs-toggle="dropdown" aria-expanded="false" style=" background-color:#CDC1FF;">
                                    Filter by Rating
                                </button>
                                <ul class="dropdown-menu ">
                                    <li><a class="dropdown-item" href="#" data-filter="*">Show All</a></li>
                                    <li><a class="dropdown-item" href="#" data-filter="5">⭐⭐⭐⭐⭐ (5 Stars)</a></li>
                                    <li><a class="dropdown-item" href="#" data-filter="4">⭐⭐⭐⭐ (4 Stars)</a></li>
                                    <li><a class="dropdown-item" href="#" data-filter="3">⭐⭐⭐ (3 Stars)</a></li>
                                    <li><a class="dropdown-item" href="#" data-filter="2">⭐⭐ (2 Stars)</a></li>
                                    <li><a class="dropdown-item" href="#" data-filter="1">⭐ (1 Star)</a></li>
                                </ul>
                            </div>

                            <!-- فلترة حسب الموقع -->
                            <div class="dropdown">
                                <button class="btn dropdown-toggle properties-filter" type="button" data-bs-toggle="dropdown" aria-expanded="false" style=" background-color:#CDC1FF;">
                                    Filter by Location
                                </button>
                                <ul class="dropdown-menu " id="locationFilter">
                                    <li><a class="dropdown-item" href="#" data-location="all">Show All</a></li>
                                    <li><a class="dropdown-item" href="#" data-location="Amman">Amman</a></li>
                                    <li><a class="dropdown-item" href="#" data-location="Irbid">Irbid</a></li>
                                    <li><a class="dropdown-item" href="#" data-location="Zarqa">Zarqa</a></li>
                                    <li><a class="dropdown-item" href="#" data-location="Aqaba">Aqaba</a></li>
                                </ul>
                            </div>

                        </div>

                        <!-- زر البحث على اليسار -->
                        <div class="search-container" style="display: flex;">
                            <input type="text" id="clinicSearch" class="form-control" placeholder="Search clinics...">
                            <button id="searchBtn" class="btn " style=" background-color:#CDC1FF;">Search</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <div class="row properties-box" id="clinicList">
            @foreach (var clinic in Model)
            {
                <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items">
                    <div class="item">
                        <img src="~/Img/@clinic.Image" alt="@clinic.Name" asp-append-version="true" style="width: 100%;">
                        <span class="category">@clinic.Category</span>
                        <h6>
                            <div >
                                @for (int i = 0; i < clinic.Rating; i++)
                                {
                                    <i class="fa-solid fa-star"></i>
                                }
                            </div>
                        </h6>
                        <h4><a href="#">@clinic.Name</a></h4>
                        <div style="display: flex;">
                            <i class="fa-solid fa-location-dot" style="margin-top: 5px;"></i>
                            <p style="margin-left: 5px;">@clinic.Location</p>
                        </div>
                        <div style="display: flex;">
                            <i class="fa-solid fa-clock" style="margin-top: 5px;"></i>
                            <p style="margin-left: 5px;">@clinic.WorkingHours</p>
                        </div>
                        <hr>
                        <div class="main-button">
                            <a asp-controller="Clinics" asp-action="ClinicDetails" asp-route-id="@clinic.Id">Schedule a visit</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MasterPiece/MasterPiece/Views/Clinics/PaymentConfirmation.cshtml
@{
    ViewData["Title"] = "Payment Confirmation";
}
<div class="container text-center mt-5">
    <h2>🎉 Payment Successful!</h2>
    <p>@TempData["SuccessMessage"]</p>
    <a href="/" class="btn btn-primary mt-3">Back to Home</a>
</div>